### ISSUE TITLE
Kernel panic when used on a pi 1 or pi zero

### ISSUE THREAD

**Issue by TechCom2020** [allebb/pirrot#45] opened 2022-05-19 07:13 UTC
Installed the base 32bit Raspberry OS lite, that worked in everything. 
Kernel panic happens at boot  on the pi one and zero if Pirrot is installed using instructions (git install).
Tried installing using the pi one, same thing.
larger sd card. Same thing.
Expand the file system plus all the above, same thing.
Install first on pi3, same thing
Install first on pi one, same thing.
Seems to work in a pi3. Though that's not what I want running it.

**Comment by allebb** [comment] 2022-05-19 16:23
Does the kernel panic ONLY HAPPEN when Pirrot is installed though? Or even
with the base Raspberian distro installed?

Do you have any other details (regarding the kernel panic) that you can
send me?

**Comment by TechCom2020** [comment] 2022-05-19 18:29
Base Raspbeian works before anything is installed.

![20220519_011034](https://user-images.githubusercontent.com/105844682/169373807-08af1f69-93b7-448d-9ebc-77abff513b25.jpg)

**Comment by allebb** [comment] 2022-05-23 16:57
If you get a chance, please can you try the latest v3.2.0 release (released today) and let me know if this fixes your issue? If you still experience issues I'll do a clean install on my Zero W and see if I can replicate the issue - sorry for the delay on this, I've just been super busy.

**Comment by TechCom2020** [comment] 2022-05-24 05:05
is a 4gb card large enough for this?

**Comment by allebb** [comment] 2022-06-17 17:37
Sorry, just seen this reply and although I'm not sure if you're still using Pirrot - a 4GB card is extremely small for a full OS and the dependencies required by Pirrot - I would suggest using atleast a 16GB card if possible.

**Comment by allebb** [comment] 2022-06-29 16:12
I can confirm that using the latest `dev-3.3.0` build (but will be the same for the current `latest-stable` branch too) that the RaspberryPi Zero W (with a 16GB SD card) and an adequate power supply, Raspberry Pi OS 11 (bullseye) [32bit - lite] runs Pirrot without any issues (Kernel panics).

I will close this issue as I can confirm that this isn't a Pirrot issue and instead likely caused by one of the following reasons:

1) No enough power - maybe your Micro-USB power supply isn't providing enough power to the device?
2) Your 4GB SD card wasn't big enough/ran out of space which causes the Kernel Panic(?)
3) Maybe you're running the full desktop version and the combination of Pirrot dependencies and the Desktop GUI has used up all the RAM?

Closing this issue as nothing else that I can personally do to fix this for you specifically (as it doesn't appear to be Pirrot related/I cannot reproduce).

**Closed by allebb** 2022-06-29 16:12 UTC
